services:
  - type: web
    name: file-encryptor-web
    runtime: docker
    rootDir: website
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
    healthCheckPath: /
