services:
  - type: web
    name: file-encryptor-web
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/file-encryptor-web-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
      - key: SERVER_PORT
        value: 10000
    healthCheckPath: /